name: gstudent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.107

environment:
  sdk: ">=2.6.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_spinkit: ^5.0.0
  http: ^0.13.1
  get_it: ^7.1.3
  injectable: ^1.0.4
  flutter_easyloading: ^3.0.0
#  signature: ^4.1.1
  page_view_indicator: ^2.0.4
#  animated_icon_button: ^1.0.2
  video_player: ^2.2.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  google_sign_in: ^5.1.1
  collection: ^1.15.0
  audioplayers: ^0.20.1
  image_picker: ^0.8.0+4
#  cached_network_image: ^3.1.0
  path_provider: ^2.0.1
  record: ^2.1.0+1
  speech_to_text: ^5.6.0
  flutter_bloc: ^7.0.0
  toast: ^0.1.5
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  google_fonts: ^2.1.0
  flutter_tts: ^3.2.3
  avatar_glow: ^2.0.1
  carousel_slider: ^4.0.0
  page_view_indicators: ^2.0.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_cupertino_localizations: 1.0.1
  smooth_page_indicator: ^1.0.0+2
  drag_and_drop_lists: ^0.3.2+2
  quiver: ^3.0.1+1
#  dashed_circle: ^0.0.2
  provider: ^6.0.1
  # firebase_crashlytics: ^2.4.3
  firebase_core: ^1.10.0
  zoom: ^1.0.3+5
  package_info_plus: ^1.3.0
  # flutter_facebook_auth: ^3.5.7
  firebase_auth: ^3.3.4
  url_launcher: ^6.0.17
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.5
  keyboard_utils: ^1.3.3
  jwt_decoder: ^2.0.1
  permission_handler: ^8.3.0
  record_mp3: ^3.0.0
  rxdart: ^0.27.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.0
  injectable_generator: ^1.2.2
  shared_preferences: ^0.5.4+1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # - assets/item_test.png
    - assets/moa_land.png
    - assets/moa1.jpg
    - assets/moa2.jpg
    - assets/moa3.jpg
    - assets/moa4.jpg
    - assets/moa5.jpg
    - assets/moa6.jpg
    - assets/bg_login_view.png
    - assets/bg_waiting_arena.png
    - assets/game_bg_map.png
    - assets/fly_land.png
    - assets/fly_land_lock.png
    - assets/athena_land.png
    - assets/athena_land_lock.png
    - assets/amazonica_land.png
    - assets/amazonica_land_lock.png
    - assets/isukha_land.png
    - assets/isukha_land_lock.png
    - assets/arcint_land.png
    - assets/arcint_land_lock.png
    - assets/edo_land.png
    - assets/edo_land_lock.png
    - assets/game_bg_arena.png
    - assets/game_bg_arena_light.png
    - assets/bg_result_homework.png
    - assets/game_bg_dialog_create_medium.png
    - assets/game_bg_dialog_create_long.png
    - assets/wait_for_the_match.png
    - assets/game_event_example1.png
    - assets/game_event_example2.png
    - assets/bg_notification.png
    - assets/game_bg_info_clan.png
    - assets/map_master.png
    - assets/bg_route.png
    - assets/game_bg_login.png
    - assets/img_create_clan.png
    - assets/img_join_clan.png
    - assets/bg_notification_large.png
    - assets/bg_notification_medium.png
    - assets/images/title_result.png
    - assets/bg_unlock_island.png
    - assets/alchemist_nam.png
    - assets/warrior_nam.png
    - assets/healer_nam.png
    - assets/thief_nam.png
    - assets/thief_nu.png
    - assets/warrior_nu.png
    - assets/healer_nu.png
    - assets/alchemist_nu.png
    - assets/princess.png
    - assets/ninja_nam.png
    - assets/ninja_nu.png
    - assets/alchemist_nam_avatar.png
    - assets/warrior_nam_avatar.png
    - assets/healer_nam_avatar.png
    - assets/thief_nam_avatar.png
    - assets/thief_nu_avatar.png
    - assets/warrior_nu_avatar.png
    - assets/healer_nu_avatar.png
    - assets/alchemist_nu_avatar.png
    - assets/princess_avatar.png
    - assets/ninja_nam_avatar.png
    - assets/ninja_nu_avatar.png
    - assets/bg_badge.png
    - assets/attack_component_1.png
    - assets/attack_component_2.png
    - assets/attack_component_3.png
    - assets/bg_attack.png
    - assets/bg_revenge.png
    - assets/stick.png
    - assets/img_result_attack.png
    - assets/bg_text_attack_result.png
    - assets/bg_create_character.png
    - assets/game_bg_create_character.png
    - assets/slide1.png
    - assets/slide2.png
    - assets/slide3.png
    # - assets/slide4.png
    - assets/slide5.png
    - assets/icon_stolen_large.png
    - assets/double_swords_large.png
    - assets/bg_luyendan.png
    - assets/lo_luyendan.png
    - assets/bg_title_lose.png 
    - assets/walkthrough_chapter1.png 
    - assets/human_chapter2_1.png
    - assets/human_chapter2_2.png
    - assets/human_chapter2_3.png 
    - assets/path_chapter3.png
    - assets/bear.png
    - assets/bear2.png
    - assets/items_path_chapter3.png
    - assets/bear_chapter3.png
    - assets/bear_end.png 
    - assets/path_of_island_chapter4.png 
    - assets/item_path_chapter5.png
    - assets/component_chapter5.png
    - assets/fire_chapter5.png
    - assets/end_arrow_fire.png
    - assets/arrow_fire.png 
    - assets/wait_for_the_match_general.png
    - assets/wait_for_the_match_mvp.png
    - assets/ielts_mentor_background.png
    - assets/bg_testinput.png
    - assets/bg_route_large.jpg
    - assets/map40.jpg
    - assets/map60.jpg
    - assets/map5.png


    - assets/images/book_testinput1.png
    - assets/images/book_testinput2.png
    - assets/images/bottomleft.png
    - assets/images/bottomright.png
    - assets/images/topleft.png
    - assets/images/topright.png
    - assets/images/left.png
    - assets/images/bottom.png
    - assets/images/bg_dialog_send_invite.png
    - assets/images/character_landing.png
    - assets/images/character_landing2.png
    - assets/images/game_bg_bottom.png
    - assets/images/game_bg_header.png
    - assets/images/game_bg_rank.png
    - assets/images/game_character_icon.png
    - assets/images/game_fight_icon.png
    - assets/images/game_inventory_icon.png
    - assets/images/game_loa_icon.png
    - assets/images/game_map_icon.png
    - assets/images/game_mission.png
    - assets/images/game_noti_icon.png
    - assets/images/game_setting_icon.png
    - assets/images/game_clan_icon.png
    - assets/images/game_character.png
    - assets/images/game_xu.png
    - assets/images/game_bg_notification.png
    - assets/images/game_bg_member_clan.png
    - assets/images/game_bottom_bar_clan.png
    - assets/images/game_calendar.png
    - assets/images/game_diary.png
    - assets/images/game_event.png
    - assets/images/game_info.png
    - assets/images/game_ranking.png
    - assets/images/game_close_dialog_clan.png
    - assets/images/button_drop_down.png
    - assets/images/game_border_avatar_clan.png
    - assets/images/game_border_avatar_member.png
    - assets/images/game_border_progress.png
    - assets/images/game_bg_title_user.png
    - assets/images/game_bg_popup.png
    - assets/images/game_bg_content_popup.png
    - assets/images/ellipse.png
    - assets/images/icon_add.png
    - assets/images/icon_off.png
    - assets/images/icon_hiep_uoc.png
    - assets/images/icon_musical.png
    - assets/images/icon_game_password.png
    - assets/images/game_icon_notification.png
    - assets/images/game_bg_victory.png
    - assets/images/game_background__center_progress.png
    - assets/images/game_background__first_progress.png
    - assets/images/game_background__last_progress.png
    - assets/images/mai.png
    - assets/images/game_select_character_left.png
    - assets/images/game_select_character_right.png
    - assets/images/ic_commander.png
    - assets/images/ic_grandmaster.png
    - assets/images/ic_hardened.png
    - assets/images/ic_intern.png
    - assets/images/ic_king.png
    - assets/images/ic_master.png
    - assets/images/ic_newbie.png
    - assets/images/ic_regular.png
    - assets/images/ic_rookie.png
    - assets/images/ic_specialist.png
    - assets/images/ic_superior.png
    - assets/images/ic_veteran.png
    - assets/images/game_button_back.png
    - assets/images/game_avatar_character.png
    - assets/images/bg_guild_arena.png
    - assets/images/icon_fb.png
    - assets/images/icon_ig.png
    - assets/images/icon_apple.png
    - assets/images/eclipse_login.png
    - assets/images/retangcle_arena_fight.png
    - assets/images/icon_wrong.png
    - assets/images/icon_true.png
    - assets/images/gold.png
    - assets/images/silver.png
    - assets/images/copper.png
    - assets/images/icon_find.png
    - assets/images/ranking_clan_title.png
    - assets/images/icon_edutalk_pact.png
    - assets/images/icon_emoji.png
    - assets/images/bg_content_result_homework.png
    - assets/images/icon_listening.png
    - assets/images/icon_reading.png
    - assets/images/icon_lesson_future.png
    - assets/images/icon_lesson_current.png
    - assets/images/button_long_blue.png
    - assets/images/bg_info_item_inven.png
    - assets/images/bg_content_dialog.png
    - assets/images/button_small_blue.png
    - assets/images/button_small_yellow.png
    - assets/images/button_small_gray.png
    - assets/images/button_yellow_long.png
    - assets/images/icon_checkbox.png
    - assets/images/icon_checkbox_checked.png
    - assets/images/bg_finish_mission.png
    - assets/images/ranking_top1.png
    - assets/images/ranking_top2.png
    - assets/images/ranking_top3.png
    - assets/images/ic_training_speed.png
    - assets/images/ic_training_test.png
    - assets/images/ic_training_vocab.png
    - assets/images/icon_current_lesson.png
    - assets/images/ic_clock.png
    - assets/images/ic_hourglass.png
    - assets/images/ic_ranking.png
    - assets/images/ic_medal.png
    - assets/images/bg_ic_result.png
    - assets/images/icon_forge.png
    - assets/images/icon_knitting_practice.png
    - assets/images/icon_steal.png
    - assets/images/icon_encourage.png
    - assets/images/icon_defend.png
    - assets/images/icon_title_send_invite.png
    - assets/images/ic_swords.png
    - assets/images/hp_bar.png
    - assets/images/mp_bar.png
    - assets/images/icon_sword_large.png
    - assets/images/boy.png
    - assets/images/chest.png
    - assets/images/girl.png
    - assets/images/plus_exp.png
    - assets/images/waiting_rank.png
    - assets/images/waiting_target.png
    - assets/images/banhmichuyenngu.png
    - assets/images/bikipdotpha.png
    - assets/images/danduoccaocap.png
    - assets/images/danduocsocap.png
    - assets/images/danduocthancap.png
    - assets/images/donghongungdong.png
    - assets/images/goiy5050.png
    - assets/images/guongnhanban.png
    - assets/images/hopquamayman.png
    - assets/images/hopquamaymancaocap.png
    - assets/images/ngoisaohivong.png
    - assets/images/thebaihanhphuc.png
    - assets/images/hopquamaymanthancap.png
    - assets/images/icon_rules.png
    - assets/images/icon_stolen_small.png
    - assets/images/icon_trainning.png
    - assets/images/icon_file_info.png
    - assets/images/ic_letter.png
    - assets/images/swords_icon.png
    - assets/images/item_luyendan1.png
    - assets/images/item_luyendan2.png
    - assets/images/item_luyendan3.png
    - assets/images/item_luyendan4.png
    - assets/images/item_luyendan5.png
    - assets/images/icon_mvp.png
    - assets/images/icon_general.png
    - assets/images/icon_member.png
    - assets/images/bg_status.png
    - assets/images/horn_rank.png
    - assets/images/horn_win_lose.png
    - assets/images/icon_status_shield.png
    - assets/images/item1_chapter_1.png
    - assets/images/item_chapter2.png
    - assets/images/ohara_teacher.png
    - assets/images/ohara_teacher_2.png
    - assets/images/kogi_1.png
    - assets/images/kogi_2.png
    - assets/images/arrow_bottom.png
    - assets/images/item_2_chapter1.png
    - assets/images/item1_chapter1_large.png
    - assets/images/thinking_gate.png
    - assets/images/thinking_team.png
    - assets/images/thinking_arrow.png
    - assets/images/thinking_stone.png
    - assets/images/gate.png
    - assets/images/icon_target.png
    - assets/images/item1_chapter3.png
    - assets/images/item2_chapter3.png
    - assets/images/item3_chapter3.png
    - assets/images/item4_chapter3.png
    - assets/images/item5_chapter3.png
    - assets/images/viking_teacher1.png
    - assets/images/ali_teacher.png
    - assets/images/flying_carpet.png
    - assets/images/path_chapter5.png
    - assets/images/shinobi_teacher.png
    - assets/images/shinobi_teacher_2.png
    - assets/images/border_badge.png
    - assets/images/icon_word_vocab.png
    - assets/images/bg_content_reward.png
    - assets/images/light_fare.png

    - assets/images/earthquakeranking.png
    - assets/images/godriddle.png
    - assets/images/guild.png
    - assets/images/kingspeed.png
    - assets/images/knightcorps.png
    - assets/images/languageexplorer.png
    - assets/images/legendofranking.png
    - assets/images/logindaily.png
    - assets/images/mapmater.png
    - assets/images/mastercollector.png
    - assets/images/poseidon.png
    - assets/images/prodigyenglish.png
    - assets/images/reviewexperts.png
    - assets/images/strongman.png
    - assets/images/superfast.png
    - assets/images/superspeedmemory.png
    - assets/images/superstar.png
    - assets/images/survivalmaster.png
    - assets/images/top50.png
    - assets/images/tsunami.png

    - assets/images/alice.png
    - assets/images/chapte6_material1.png
    - assets/images/chapte6_material2.png
    - assets/images/chapte6_material3.png
    - assets/images/chapte6_material4.png
    - assets/images/chapte6_material5.png
    - assets/images/chapter6_component1.png
    - assets/images/chapter6_component2.png
    - assets/images/chapter6_stone.png
    - assets/images/chapter6_stone2.png

    - assets/images/icon_mic.png
    - assets/images/icon_question_per_min.png
    - assets/images/icon_tick_score.png
    - assets/images/icon_total_time.png
    - assets/images/icon_writing.png
    - assets/images/icon_google.png
    - assets/images/teacher_island1.png
    - assets/images/teacher_island2.png
    - assets/images/teacher_island3.png
    - assets/images/teacher_island4.png
    - assets/images/teacher_island5.png
    - assets/images/teacher_island6.png

    - assets/images/educoach.png
    - assets/images/ieltmemtor.png
    - assets/images/pin.png
    - assets/images/ic_center.png
    - assets/images/ic_time_test.png

    - assets/images/bottomleft.png
    - assets/images/bottomright.png
    - assets/images/doc.png
    - assets/images/ngang.png
    - assets/images/topleft.png
    - assets/images/topright.png
    - assets/images/zoom_meeting.png
    - assets/images/book.png
    - assets/images/background_level.png

  fonts:
    - family: IconStatusClan
      fonts:
        - asset: assets/fonts/IconStatusClan.ttf
    - family: UTMThanChienTranh
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
          weight: 400
    - family: SourceSerifPro
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700


        # - asset: assets/fonts/Nunito-Bold.ttf
        # - asset: assets/fonts/Nunito-Bold.ttf
        # - asset: assets/fonts/Nunito-Bold.ttf
        # - asset: assets/fonts/Nunito-Bold.ttf
        # - asset: assets/fonts/Nunito-Bold.ttf
        # - asset: assets/fonts/Nunito-Bold.ttf
        #   style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
