String defineBadgeById(int id) {
  switch (id) {
    case 1:
      return 'assets/images/logindaily.png';
    case 2:
      return 'assets/images/mapmater.png';
    case 3:
      return 'assets/images/survivalmaster.png';
    case 4:
      return 'assets/images/languageexplorer.png';
    case 5:
      return 'assets/images/mastercollector.png';
    case 6:
      return 'assets/images/superspeedmemory.png';
    case 7:
      return 'assets/images/strongman.png';
    case 8:
      return 'assets/images/superfast.png';
    case 9:
      return 'assets/images/kingspeed.png';
    case 0:
      return 'assets/images/prodigyenglish.png';
    case 11:
      return 'assets/images/guild.png';
    case 12:
      return 'assets/images/poseidon.png';
    case 13:
      return 'assets/images/knightcorps.png';
    case 14:
      return 'assets/images/tsunami.png';
    case 15:
      return 'assets/images/top50.png';
    case 16:
      return 'assets/images/earthquakeranking.png';
    case 17:
      return 'assets/images/legendofranking.png';
    case 18:
      return 'assets/images/game_button_back.png';
    case 19:
      return 'assets/images/godriddle.png';
    case 20:
      return 'assets/images/reviewexperts.png';
    case 21:
      return 'assets/images/superstar.png';
    case 22:
      return 'assets/images/ic_newbie.png';
    case 23:
      return 'assets/images/ic_rookie.png';
    case 24:
      return 'assets/images/ic_intern.png';
    case 25:
      return 'assets/images/ic_regular.png';
    case 26:
      return 'assets/images/ic_hardened.png';
    case 27:
      return 'assets/images/ic_veteran.png';
    case 28:
      return 'assets/images/ic_superior.png';
    case 29:
      return 'assets/images/ic_commander.png';
    case 30:
      return 'assets/images/ic_specialist.png';
    case 31:
      return 'assets/images/ic_master.png';
    case 32:
      return 'assets/images/ic_king.png';
    default:
      return 'assets/images/ic_grandmaster.png';
  }
}
